### PR TITLE
Trying homu

### PR DESCRIPTION
**Pull request by matthew-brett**

### CODE REVIEW

**Comment by matthew-brett** [comment]
r+

**Comment by matthew-brett** [comment]
@matthew-brett r+

**Comment by matthew-brett** [comment]
@matthew-brett r+

**Comment by matthew-brett** [comment]
@matthew-brett r+

**Comment by matthew-brett** [comment]
@matthew-brett r+

**Comment by matthew-brett** [comment]
@matthew-brett r+

**Comment by matthew-brett** [comment]
@matthew-brett r+

**Comment by matthew-brett** [comment]
@matthew-brett r+

**Comment by matthew-brett** [comment]
@matthew-brett r+

**Comment by matthew-brett** [comment]
matthew-brett r+

**Comment by matthew-brett** [comment]
@matthew-brett r+

**Comment by matthew-brett** [comment]
@matthew-brett r=matthew-brett

**Comment by stefanv** [comment]
@matthew-brett r+

**Comment by matthew-brett** [comment]
:pushpin: Commit 6157794 has been approved by `stefanv`

**Comment by matthew-brett** [comment]
:hourglass: Testing commit 6157794 with merge 9ddfa73...

**Comment by stefanv** [comment]
@matthew-brett r-

**Comment by matthew-brett** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/matthew-brett/transforms3d/builds/103750854)

**Comment by nibotmi** [comment]
@nibotmi retry

**Comment by stefanv** [comment]
@nibotmi retry

**Comment by stefanv** [comment]
@nibotmi r+

**Comment by nibotmi** [comment]
:pushpin: Commit 6157794 has been approved by `stefanv`

**Comment by stefanv** [comment]
@nibotmi r-

**Comment by stefanv** [comment]
@nibotmi retry

**Comment by stefanv** [comment]
@nibotmi r+

**Comment by nibotmi** [comment]
:pushpin: Commit 6157794 has been approved by `stefanv`

**Comment by nibotmi** [comment]
:hourglass: Testing commit 6157794 with merge e4a9ad0...

**Comment by stefanv** [comment]
@nibotmi r-

**Comment by nibotmi** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/matthew-brett/transforms3d/builds/103754282)

**Comment by nibotmi** [comment]
:umbrella: The latest upstream changes (presumably e402e56) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by matthew-brett** [comment]
I didn't find much use for these bots elsewhere, so dropping here.

**Pull request closed without merging**
